spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://database-mysql:3306/blogsite?createDatabaseIfNotExist=true
    username: admin
    password: root
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  h2:
    console:
      enabled: true

axon:
  axonserver:
    servers: axonserver:8124


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  #    service-url:
  #      default-zone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true